### ISSUE TITLE
<BE> 공부방 멤버 채팅서버와 연결한다.

### ISSUE THREAD

**Issue by solyrion** [boostcampwm-2024/web24-GOMZ#80]
## story
유저는 공부방에 입장할 수 있다.
## task
공부방 멤버 채팅서버와 연결한다.
## 예상 소요 시간
1시간
## 개발할 사항

- 개발할 사항1
- 개발할 사항2
- ...

**Comment by Choi-JY1107** [comment]
#45 와 같은 내용
